set tabstop=4
set shiftwidth=4

let g:team_highlight_colors = [
      \   'ctermfg=darkred         guifg=darkred',
      \   'ctermfg=darkyellow      guifg=darkyellow',
      \   'ctermfg=darkgreen       guifg=darkgreen',
      \   'ctermfg=darkcyan        guifg=darkcyan',
      \   'ctermfg=darkblue        guifg=darkblue',
      \   'ctermfg=darkmagenta     guifg=darkmagenta',
      \   'ctermfg=darkgrey        guifg=darkgrey',
    \ ]

function! s:mod(n,m)
  return ((a:n % a:m) + a:m) % a:m
endfunction

function! s:TeamHighlights()
  let l:team_names_hyperbase = system('echo "$(yq -M "keys | join(\" \")" TEAMS.yaml)"')

  let l:length_of_colors = len(g:team_highlight_colors)

  let l:color_idx = 0
  for l:higlight_config in g:team_highlight_colors
    let l:highlight_name = "TeamColor" . l:color_idx
    execute "highlight " . l:highlight_name . " " . g:team_highlight_colors[l:color_idx]
    let l:color_idx = s:mod(l:color_idx + 1, l:length_of_colors)
  endfor

  let l:color_idx = 0
  for l:team_name_line in split(l:team_names_hyperbase, " ")
    let l:highlight_name = "TeamColor" . l:color_idx
    call matchadd(l:highlight_name, l:team_name_line, 70 + l:color_idx)
    let l:color_idx = s:mod(l:color_idx + 1, l:length_of_colors)
  endfor
endfunction

autocmd VimEnter * call s:TeamHighlights()
